spring:
  ai:
    dashscope:
      api-key: sk-2553356e8de943c59d2a37a571dfb85c
  profiles:
    active: local
server:
  port: 8123
  servlet:
    context-path: /api
  # springdoc-openapi ??????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.dsj.aiagent.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn
